### ISSUE TITLE
MONA error: Could not find the value .*DFA for formula with free variables:[\s]*(.*?)\n.*, in the text provided

### ISSUE THREAD

**Issue by isaac-mackey2** [whitemech/LTLf2DFA#15]
I'm trying to use the ltlf2dfa package to generate an jpg/png image of automata.

There may be a problem with parsing the MONA output in ltlf2dfa/ltlf2dfa.py.

Here is a Minimal Working Example and Error Message:

>>> from LTLf2DFA.ltlf2dfa.parser.ltlf import LTLfParser
>>> fparser = LTLfParser()
>>> formula_str_0 = "G(a -> X b)"
>>> formula_0 = fparser(formula_str_0)
>>> formula_0.to_dfa()

Error Message:
Could not find the value .*DFA for formula with free variables:[\s]*(.*?)\n.*, in the text provided
Could not find the value .*Accepting states:[\s]*(.*?)\n.*, in the text provided
'digraph MONA_DFA {\n rankdir = LR;\n center = true;\n size = "7.5,10.5";\n edge [fontname = Courier];\n node [height = .5, width = .5];\n node [shape = doublecircle]; 0.0;\n node [shape = circle]; 1;\n init [shape = plaintext, label = ""];\n init -> 1;\n}'

**Comment by isaac-mackey2** [comment]
Never mind, I think I had MONA installed incorrectly

**Comment by USTCzzl** [comment]
> Never mind, I think I had MONA installed incorrectly

Hi,  Have you solved this problem?

**Comment by francescofuggitti** [comment]
This error is solved with a proper installation of the MONA library. Please, check the installation instruction [here](https://www.brics.dk/mona/download.html).

Using Linux or macOS is recommended.
