### ISSUE TITLE
MONA translation of Weak Next

### ISSUE THREAD

**Issue by insmdl00** [whitemech/LTLf2DFA#23]
Hello,

I just realised that the translation of weak next into MONA is not correct. 

I think the implementation should be 

 def to_mona(self, v="0") -> str:
        """Return the MONA encoding of an LTLf WeakNext formula."""
        ex_var = new_var(v)
        if v != "0":
            return "(({1} = max($)) | (ex1 {0}: {0}={1}+1 & {2}))".format(
                ex_var, v, self.f.to_mona(ex_var)
            )
        else:
            return "((0 = max($)) | (ex1 {0}: {0}=1 & {1}))".format(
                ex_var, self.f.to_mona(ex_var)
            )

instead of the current one. Could you please tell me if I am right ?

Best,
Martin.

**Comment by francescofuggitti** [comment]
same as issue #24
