### ISSUE TITLE
MONA translation of weak next

### ISSUE THREAD

**Issue by insmdl00** [whitemech/LTLf2DFA#24]
Hello,

I just realised that the translation of weak next into MONA is not correct. 

I think the implementation should be 

 def to_mona(self, v="0") -> str:
        """Return the MONA encoding of an LTLf WeakNext formula."""
        ex_var = new_var(v)
        if v != "0":
            return "(({1} = max($)) | (ex1 {0}: {0}={1}+1 & {2}))".format(
                ex_var, v, self.f.to_mona(ex_var)
            )
        else:
            return "((0 = max($)) | (ex1 {0}: {0}=1 & {1}))".format(
                ex_var, self.f.to_mona(ex_var)
            )

instead of the current one. Could you please tell me if I am right ?

Best,
Martin.

**Comment by francescofuggitti** [comment]
Hi Martin, 

Thanks for reaching out.

As far as I've seen, the difference between my implementation and yours is just the presence of wrapping redundant parentheses. Could you confirm that? If this was the error, thanks for spotting it. It is going to be fixed in the next release.

Cheers,
Francesco

**Comment by insmdl00** [comment]
Hi Francesco, 

in the current version of the code if v != "0" you return 
return "((0 = max($)) | (ex1 {0}: {0}={1}+1 & {2}))".format(
                ex_var, v, self.f.to_mona(ex_var)
            )

I think the 0=max($) in the resturn should be turned into {1} = max($). You need to consider that the current first-order variable v can be at the end of the trace. right ?

**Comment by francescofuggitti** [comment]
Oh, I see the problem. Thanks for letting me know. You're right, but you're referring to the master branch, which is indeed buggy. The fix has been already applied to the develop branch! 

I recommend to use the develop branch, which covers several bugs found, and it's more updated. I will eventually merge the develop into the master as soon as possible.
