### ISSUE TITLE
mona memory explosion 

### ISSUE THREAD

**Issue by melbrbry** [whitemech/LTLf2DFA#39]
there is a memory explosion from MONA when trying to translate relatively big LTLf formula e.g.

formula = "F(at_p2 & X(collect & XF(at_m2 & X(deliver & \
          XF(at_p1 & X(collect & XF(at_m2 & X(deliver & \
          XF(at_p1 & X(collect & XF(at_m1 & X(deliver & \
          XF(at_p3 & X(collect & XF(at_m3 & X(deliver & \
          XF(at_p1 & X(collect & XF(at_m2 & X(deliver))))))))))))))))))))"

I use -s option to debug mona and it seems that the computation are all fine until it reaches 99% then it stucks there and eats all the memory. I even tried using 128GB memory, but the same bug persists. I wonder if this error is from mona or the input generated by the LTLf2DFA tool.

the full verbosing file attached.
[log_output_file.txt](https://github.com/whitemech/LTLf2DFA/files/8903599/log_output_file.txt)

**Comment by francescofuggitti** [comment]
Hi @melbrbry,

thanks for reporting this issue. Have you tried installing MONA from [https://github.com/whitemech/MONA](https://github.com/whitemech/MONA)? In this forked version, we modified some parameters to get MONA working with bigger formulas.

Let me know if that solves your issue!

**Comment by francescofuggitti** [comment]
I'm going to close this issue now. If you think there's still a problem with the translation, let me know.

**Comment by melbrbry** [comment]
Sorry for the late answer. This does not solve the issue, unfortunately.
