### ISSUE TITLE
Could not find the value .*DFA for formula with free variables:[\s]*(.*?)\n.*, in the text provided

### ISSUE THREAD

**Issue by syemichel** [whitemech/LTLf2DFA#44]
I use
 "dfa = formula.to_dfa()
print(dfa)"
Then  I get "Could not find the value .*DFA for formula with free variables:[\s]*(.*?)\n.*, in the text provided
Could not find the value .*Accepting states:[\s]*(.*?)\n.*, in the text provided"
It's the problem of mona's installation?

**Comment by francescofuggitti** [comment]
Yes, please double-check that MONA is correctly installed and available on your PATH

**Comment by BurmanT** [comment]
I had the same error, how are you checking if MONA is correctly installed?

**Comment by francescofuggitti** [comment]
From the folder where you call the program (and therefore where MONA is called), you can type `mona`. If mona is properly installed, then you should get the following output:
![image](https://user-images.githubusercontent.com/29372925/217764650-d01c0756-ea92-4040-b6b2-e2c2de3c4e88.png)
